---
language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec rake spec
after_failure: "cat /home/travis/build/paramadeep/poisol/log/poisol_stub.log; cat /home/travis/build/paramadeep/poisol/log/poisol_webrick.log;"
